language: ruby
rvm:
  - 2.4.2
services:
  - postgresql
before_install:
  - cp config/database.travis.yml spec/dummy/config/database.yml
  - psql -c 'create database goblog_test;' -U postgres
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rspec
after_success:
  - coveralls
